//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinozal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kinozal()
        {
            this.seans = new HashSet<seans>();
        }
    
        public int Id_kinozal { get; set; }
        public short number { get; set; }
        public int capasity { get; set; }
        public int KinoteatrId_kinoteatr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seans> seans { get; set; }
        public virtual Kinoteatr Kinoteatr { get; set; }
    }
}
