//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class seans
    {
        public int Id_seans { get; set; }
        public System.DateTime tame_date { get; set; }
        public int KinozalId_kinozal { get; set; }
        public int BiletId_bilet { get; set; }
    
        public virtual Kinozal Kinozal { get; set; }
        public virtual Bilet Bilet { get; set; }
    }
}
